#!/bin/sh

set -x
set -e

ZIG="zig-linux-x86_64-0.9.0-dev.1175+1f2f9f05c"
wget -nv "https://ziglang.org/builds/$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

QEMUBASE="qemu-linux-x86_64-6.1.0.1"
wget -nv "https://ziglang.org/deps/$QEMUBASE.tar.xz"
tar xf "$QEMUBASE.tar.xz"
export PATH="$(pwd)/$QEMUBASE/bin:$PATH"

zig build test -Denable-qemu

