#!/bin/sh

set -x
set -e

ZIG="zig-macos-x86_64-0.9.0-dev.1175+1f2f9f05c"
curl -L "https://ziglang.org/builds/$ZIG.tar.xz" -o "$ZIG.tar.xz"
tar xf "$ZIG.tar.xz"
export PATH="$(pwd)/$ZIG:$PATH"

zig build test
