#!/bin/sh

set -x
set -e

ZIG="zig-windows-x86_64-0.9.0-dev.1903+2af94e76a"
curl -L "https://ziglang.org/builds/$ZIG.zip" -o "$ZIG.zip"
7z x "$ZIG.zip"
export PATH="$(pwd)/$ZIG:$PATH"

zig build test
